
services:
  valkey:
    image: valkey/valkey:latest
    container_name: valkey
    ports:
      - "6379:6379"
    environment:
      - VALKEY_PASSWORD=
    volumes:
      - valkey_data:/data
    restart: unless-stopped

volumes:
  valkey_data: